name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v4
      #     run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
  
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          file: ./docker/Dockerfile
          push: push
          tags: darabas/darabas-devops-satc-a3:latest
